# for what versions are available, see:
# https://github.com/travis-ci/travis-cookbooks/blob/master/ci_environment/perlbrew/attributes/multi.rb
language: perl
perl:
    #- dev
    - "5.19"
    #- stable
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"
install:
    - cpanm -q --notest Dist::Zilla
    - dzil authordeps --missing | grep -v '^inc::' | cpanm -q --notest
    - dzil listdeps --author --missing | cpanm -q --notest
script:
    - dzil test --author --smoke
